// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __imager_h__
#define __imager_h__

#include "imager_RcppExports.h"

#endif // __imager_h__
