// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/imager.h"
#include <Rcpp.h>

using namespace Rcpp;

// RGBtoHSL
NumericVector RGBtoHSL(NumericVector im);
RcppExport SEXP imager_RGBtoHSL(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoHSL(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtoXYZ
NumericVector RGBtoXYZ(NumericVector im);
RcppExport SEXP imager_RGBtoXYZ(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoXYZ(im));
    return rcpp_result_gen;
END_RCPP
}
// XYZtoRGB
NumericVector XYZtoRGB(NumericVector im);
RcppExport SEXP imager_XYZtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(XYZtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// HSLtoRGB
NumericVector HSLtoRGB(NumericVector im);
RcppExport SEXP imager_HSLtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(HSLtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtoHSV
NumericVector RGBtoHSV(NumericVector im);
RcppExport SEXP imager_RGBtoHSV(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoHSV(im));
    return rcpp_result_gen;
END_RCPP
}
// HSVtoRGB
NumericVector HSVtoRGB(NumericVector im);
RcppExport SEXP imager_HSVtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(HSVtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtoHSI
NumericVector RGBtoHSI(NumericVector im);
RcppExport SEXP imager_RGBtoHSI(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoHSI(im));
    return rcpp_result_gen;
END_RCPP
}
// HSItoRGB
NumericVector HSItoRGB(NumericVector im);
RcppExport SEXP imager_HSItoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(HSItoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtosRGB
NumericVector RGBtosRGB(NumericVector im);
RcppExport SEXP imager_RGBtosRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtosRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// sRGBtoRGB
NumericVector sRGBtoRGB(NumericVector im);
RcppExport SEXP imager_sRGBtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(sRGBtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtoYCbCr
NumericVector RGBtoYCbCr(NumericVector im);
RcppExport SEXP imager_RGBtoYCbCr(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoYCbCr(im));
    return rcpp_result_gen;
END_RCPP
}
// YCbCrtoRGB
NumericVector YCbCrtoRGB(NumericVector im);
RcppExport SEXP imager_YCbCrtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(YCbCrtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtoYUV
NumericVector RGBtoYUV(NumericVector im);
RcppExport SEXP imager_RGBtoYUV(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoYUV(im));
    return rcpp_result_gen;
END_RCPP
}
// YUVtoRGB
NumericVector YUVtoRGB(NumericVector im);
RcppExport SEXP imager_YUVtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(YUVtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// LabtoRGB
NumericVector LabtoRGB(NumericVector im);
RcppExport SEXP imager_LabtoRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(LabtoRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// RGBtoLab
NumericVector RGBtoLab(NumericVector im);
RcppExport SEXP imager_RGBtoLab(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(RGBtoLab(im));
    return rcpp_result_gen;
END_RCPP
}
// LabtoXYZ
NumericVector LabtoXYZ(NumericVector im);
RcppExport SEXP imager_LabtoXYZ(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(LabtoXYZ(im));
    return rcpp_result_gen;
END_RCPP
}
// XYZtoLab
NumericVector XYZtoLab(NumericVector im);
RcppExport SEXP imager_XYZtoLab(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(XYZtoLab(im));
    return rcpp_result_gen;
END_RCPP
}
// LabtosRGB
NumericVector LabtosRGB(NumericVector im);
RcppExport SEXP imager_LabtosRGB(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(LabtosRGB(im));
    return rcpp_result_gen;
END_RCPP
}
// sRGBtoLab
NumericVector sRGBtoLab(NumericVector im);
RcppExport SEXP imager_sRGBtoLab(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(sRGBtoLab(im));
    return rcpp_result_gen;
END_RCPP
}
// getXc
NumericVector getXc(int x, int y, int z, int c);
RcppExport SEXP imager_getXc(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(getXc(x, y, z, c));
    return rcpp_result_gen;
END_RCPP
}
// getYc
NumericVector getYc(int x, int y, int z, int c);
RcppExport SEXP imager_getYc(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(getYc(x, y, z, c));
    return rcpp_result_gen;
END_RCPP
}
// getZc
NumericVector getZc(int x, int y, int z, int c);
RcppExport SEXP imager_getZc(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(getZc(x, y, z, c));
    return rcpp_result_gen;
END_RCPP
}
// getCc
NumericVector getCc(int x, int y, int z, int c);
RcppExport SEXP imager_getCc(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(getCc(x, y, z, c));
    return rcpp_result_gen;
END_RCPP
}
// display_
void display_(NumericVector im, bool rescale);
RcppExport SEXP imager_display_(SEXP imSEXP, SEXP rescaleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< bool >::type rescale(rescaleSEXP);
    display_(im, rescale);
    return R_NilValue;
END_RCPP
}
// display_list
void display_list(List imlist);
RcppExport SEXP imager_display_list(SEXP imlistSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type imlist(imlistSEXP);
    display_list(imlist);
    return R_NilValue;
END_RCPP
}
// play
void play(NumericVector vid, bool loop, unsigned long delay, bool normalise);
RcppExport SEXP imager_play(SEXP vidSEXP, SEXP loopSEXP, SEXP delaySEXP, SEXP normaliseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vid(vidSEXP);
    Rcpp::traits::input_parameter< bool >::type loop(loopSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< bool >::type normalise(normaliseSEXP);
    play(vid, loop, delay, normalise);
    return R_NilValue;
END_RCPP
}
// select
NumericVector select(NumericVector im, int type);
RcppExport SEXP imager_select(SEXP imSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(select(im, type));
    return rcpp_result_gen;
END_RCPP
}
// bucket_fill
NumericVector bucket_fill(NumericVector im, int x, int y, int z, NumericVector color, float opacity, float sigma, bool high_connexity);
RcppExport SEXP imager_bucket_fill(SEXP imSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP colorSEXP, SEXP opacitySEXP, SEXP sigmaSEXP, SEXP high_connexitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    Rcpp::traits::input_parameter< float >::type opacity(opacitySEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type high_connexity(high_connexitySEXP);
    rcpp_result_gen = Rcpp::wrap(bucket_fill(im, x, y, z, color, opacity, sigma, high_connexity));
    return rcpp_result_gen;
END_RCPP
}
// bucket_select
LogicalVector bucket_select(NumericVector im, int x, int y, int z, float sigma, bool high_connexity);
RcppExport SEXP imager_bucket_select(SEXP imSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP sigmaSEXP, SEXP high_connexitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type high_connexity(high_connexitySEXP);
    rcpp_result_gen = Rcpp::wrap(bucket_select(im, x, y, z, sigma, high_connexity));
    return rcpp_result_gen;
END_RCPP
}
// deriche
NumericVector deriche(NumericVector im, float sigma, int order, char axis, bool neumann);
RcppExport SEXP imager_deriche(SEXP imSEXP, SEXP sigmaSEXP, SEXP orderSEXP, SEXP axisSEXP, SEXP neumannSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< bool >::type neumann(neumannSEXP);
    rcpp_result_gen = Rcpp::wrap(deriche(im, sigma, order, axis, neumann));
    return rcpp_result_gen;
END_RCPP
}
// vanvliet
NumericVector vanvliet(NumericVector im, float sigma, int order, char axis, bool neumann);
RcppExport SEXP imager_vanvliet(SEXP imSEXP, SEXP sigmaSEXP, SEXP orderSEXP, SEXP axisSEXP, SEXP neumannSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< bool >::type neumann(neumannSEXP);
    rcpp_result_gen = Rcpp::wrap(vanvliet(im, sigma, order, axis, neumann));
    return rcpp_result_gen;
END_RCPP
}
// isoblur
NumericVector isoblur(NumericVector im, float sigma, bool neumann, bool gaussian);
RcppExport SEXP imager_isoblur(SEXP imSEXP, SEXP sigmaSEXP, SEXP neumannSEXP, SEXP gaussianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type neumann(neumannSEXP);
    Rcpp::traits::input_parameter< bool >::type gaussian(gaussianSEXP);
    rcpp_result_gen = Rcpp::wrap(isoblur(im, sigma, neumann, gaussian));
    return rcpp_result_gen;
END_RCPP
}
// medianblur
NumericVector medianblur(NumericVector im, int n, float threshold);
RcppExport SEXP imager_medianblur(SEXP imSEXP, SEXP nSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< float >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(medianblur(im, n, threshold));
    return rcpp_result_gen;
END_RCPP
}
// boxblur
NumericVector boxblur(NumericVector im, float boxsize, bool neumann);
RcppExport SEXP imager_boxblur(SEXP imSEXP, SEXP boxsizeSEXP, SEXP neumannSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type boxsize(boxsizeSEXP);
    Rcpp::traits::input_parameter< bool >::type neumann(neumannSEXP);
    rcpp_result_gen = Rcpp::wrap(boxblur(im, boxsize, neumann));
    return rcpp_result_gen;
END_RCPP
}
// imlap
NumericVector imlap(NumericVector im);
RcppExport SEXP imager_imlap(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(imlap(im));
    return rcpp_result_gen;
END_RCPP
}
// boxblur_xy
NumericVector boxblur_xy(NumericVector im, float sx, float sy, bool neumann);
RcppExport SEXP imager_boxblur_xy(SEXP imSEXP, SEXP sxSEXP, SEXP sySEXP, SEXP neumannSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< float >::type sy(sySEXP);
    Rcpp::traits::input_parameter< bool >::type neumann(neumannSEXP);
    rcpp_result_gen = Rcpp::wrap(boxblur_xy(im, sx, sy, neumann));
    return rcpp_result_gen;
END_RCPP
}
// correlate
NumericVector correlate(NumericVector im, NumericVector filter, bool dirichlet, bool normalise);
RcppExport SEXP imager_correlate(SEXP imSEXP, SEXP filterSEXP, SEXP dirichletSEXP, SEXP normaliseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< bool >::type dirichlet(dirichletSEXP);
    Rcpp::traits::input_parameter< bool >::type normalise(normaliseSEXP);
    rcpp_result_gen = Rcpp::wrap(correlate(im, filter, dirichlet, normalise));
    return rcpp_result_gen;
END_RCPP
}
// convolve
NumericVector convolve(NumericVector im, NumericVector filter, bool dirichlet, bool normalise);
RcppExport SEXP imager_convolve(SEXP imSEXP, SEXP filterSEXP, SEXP dirichletSEXP, SEXP normaliseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< bool >::type dirichlet(dirichletSEXP);
    Rcpp::traits::input_parameter< bool >::type normalise(normaliseSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve(im, filter, dirichlet, normalise));
    return rcpp_result_gen;
END_RCPP
}
// sharpen
NumericVector sharpen(NumericVector im, float amplitude, bool sharpen_type, float edge, float alpha, float sigma);
RcppExport SEXP imager_sharpen(SEXP imSEXP, SEXP amplitudeSEXP, SEXP sharpen_typeSEXP, SEXP edgeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type amplitude(amplitudeSEXP);
    Rcpp::traits::input_parameter< bool >::type sharpen_type(sharpen_typeSEXP);
    Rcpp::traits::input_parameter< float >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(sharpen(im, amplitude, sharpen_type, edge, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// get_gradient
List get_gradient(NumericVector im, std::string axes, int scheme);
RcppExport SEXP imager_get_gradient(SEXP imSEXP, SEXP axesSEXP, SEXP schemeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< std::string >::type axes(axesSEXP);
    Rcpp::traits::input_parameter< int >::type scheme(schemeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_gradient(im, axes, scheme));
    return rcpp_result_gen;
END_RCPP
}
// get_hessian
List get_hessian(NumericVector im, std::string axes);
RcppExport SEXP imager_get_hessian(SEXP imSEXP, SEXP axesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< std::string >::type axes(axesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_hessian(im, axes));
    return rcpp_result_gen;
END_RCPP
}
// diffusion_tensors
NumericVector diffusion_tensors(NumericVector im, float sharpness, float anisotropy, float alpha, float sigma, bool is_sqrt);
RcppExport SEXP imager_diffusion_tensors(SEXP imSEXP, SEXP sharpnessSEXP, SEXP anisotropySEXP, SEXP alphaSEXP, SEXP sigmaSEXP, SEXP is_sqrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type sharpness(sharpnessSEXP);
    Rcpp::traits::input_parameter< float >::type anisotropy(anisotropySEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type is_sqrt(is_sqrtSEXP);
    rcpp_result_gen = Rcpp::wrap(diffusion_tensors(im, sharpness, anisotropy, alpha, sigma, is_sqrt));
    return rcpp_result_gen;
END_RCPP
}
// haar
NumericVector haar(NumericVector im, bool inverse, int nb_scales);
RcppExport SEXP imager_haar(SEXP imSEXP, SEXP inverseSEXP, SEXP nb_scalesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< bool >::type inverse(inverseSEXP);
    Rcpp::traits::input_parameter< int >::type nb_scales(nb_scalesSEXP);
    rcpp_result_gen = Rcpp::wrap(haar(im, inverse, nb_scales));
    return rcpp_result_gen;
END_RCPP
}
// FFT_complex
List FFT_complex(NumericVector real, NumericVector imag, bool inverse, int nb_threads);
RcppExport SEXP imager_FFT_complex(SEXP realSEXP, SEXP imagSEXP, SEXP inverseSEXP, SEXP nb_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type real(realSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type imag(imagSEXP);
    Rcpp::traits::input_parameter< bool >::type inverse(inverseSEXP);
    Rcpp::traits::input_parameter< int >::type nb_threads(nb_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(FFT_complex(real, imag, inverse, nb_threads));
    return rcpp_result_gen;
END_RCPP
}
// FFT_realim
List FFT_realim(NumericVector real, bool inverse, int nb_threads);
RcppExport SEXP imager_FFT_realim(SEXP realSEXP, SEXP inverseSEXP, SEXP nb_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type real(realSEXP);
    Rcpp::traits::input_parameter< bool >::type inverse(inverseSEXP);
    Rcpp::traits::input_parameter< int >::type nb_threads(nb_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(FFT_realim(real, inverse, nb_threads));
    return rcpp_result_gen;
END_RCPP
}
// FFT_realout
NumericVector FFT_realout(NumericVector real, NumericVector imag, bool inverse, int nb_threads);
RcppExport SEXP imager_FFT_realout(SEXP realSEXP, SEXP imagSEXP, SEXP inverseSEXP, SEXP nb_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type real(realSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type imag(imagSEXP);
    Rcpp::traits::input_parameter< bool >::type inverse(inverseSEXP);
    Rcpp::traits::input_parameter< int >::type nb_threads(nb_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(FFT_realout(real, imag, inverse, nb_threads));
    return rcpp_result_gen;
END_RCPP
}
// displacement
NumericVector displacement(NumericVector sourceIm, NumericVector destIm, float smoothness, float precision, unsigned int nb_scales, unsigned int iteration_max, bool is_backward);
RcppExport SEXP imager_displacement(SEXP sourceImSEXP, SEXP destImSEXP, SEXP smoothnessSEXP, SEXP precisionSEXP, SEXP nb_scalesSEXP, SEXP iteration_maxSEXP, SEXP is_backwardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sourceIm(sourceImSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type destIm(destImSEXP);
    Rcpp::traits::input_parameter< float >::type smoothness(smoothnessSEXP);
    Rcpp::traits::input_parameter< float >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nb_scales(nb_scalesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type iteration_max(iteration_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type is_backward(is_backwardSEXP);
    rcpp_result_gen = Rcpp::wrap(displacement(sourceIm, destIm, smoothness, precision, nb_scales, iteration_max, is_backward));
    return rcpp_result_gen;
END_RCPP
}
// blur_anisotropic
NumericVector blur_anisotropic(NumericVector im, float amplitude, float sharpness, float anisotropy, float alpha, float sigma, float dl, float da, float gauss_prec, unsigned int interpolation_type, bool fast_approx);
RcppExport SEXP imager_blur_anisotropic(SEXP imSEXP, SEXP amplitudeSEXP, SEXP sharpnessSEXP, SEXP anisotropySEXP, SEXP alphaSEXP, SEXP sigmaSEXP, SEXP dlSEXP, SEXP daSEXP, SEXP gauss_precSEXP, SEXP interpolation_typeSEXP, SEXP fast_approxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type amplitude(amplitudeSEXP);
    Rcpp::traits::input_parameter< float >::type sharpness(sharpnessSEXP);
    Rcpp::traits::input_parameter< float >::type anisotropy(anisotropySEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< float >::type dl(dlSEXP);
    Rcpp::traits::input_parameter< float >::type da(daSEXP);
    Rcpp::traits::input_parameter< float >::type gauss_prec(gauss_precSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type interpolation_type(interpolation_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type fast_approx(fast_approxSEXP);
    rcpp_result_gen = Rcpp::wrap(blur_anisotropic(im, amplitude, sharpness, anisotropy, alpha, sigma, dl, da, gauss_prec, interpolation_type, fast_approx));
    return rcpp_result_gen;
END_RCPP
}
// periodic_part
NumericVector periodic_part(NumericVector im);
RcppExport SEXP imager_periodic_part(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(periodic_part(im));
    return rcpp_result_gen;
END_RCPP
}
// interp_xy
NumericVector interp_xy(NumericVector inp, NumericVector ix, NumericVector iy, int z, int c, bool cubic);
RcppExport SEXP imager_interp_xy(SEXP inpSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP zSEXP, SEXP cSEXP, SEXP cubicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inp(inpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< bool >::type cubic(cubicSEXP);
    rcpp_result_gen = Rcpp::wrap(interp_xy(inp, ix, iy, z, c, cubic));
    return rcpp_result_gen;
END_RCPP
}
// interp_xyz
NumericVector interp_xyz(NumericVector inp, NumericVector ix, NumericVector iy, NumericVector iz, int c, bool cubic);
RcppExport SEXP imager_interp_xyz(SEXP inpSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP izSEXP, SEXP cSEXP, SEXP cubicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inp(inpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iz(izSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< bool >::type cubic(cubicSEXP);
    rcpp_result_gen = Rcpp::wrap(interp_xyz(inp, ix, iy, iz, c, cubic));
    return rcpp_result_gen;
END_RCPP
}
// interp_xyzc
NumericVector interp_xyzc(NumericVector inp, NumericVector ix, NumericVector iy, NumericVector iz, IntegerVector ic, bool cubic);
RcppExport SEXP imager_interp_xyzc(SEXP inpSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP izSEXP, SEXP icSEXP, SEXP cubicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inp(inpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iz(izSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ic(icSEXP);
    Rcpp::traits::input_parameter< bool >::type cubic(cubicSEXP);
    rcpp_result_gen = Rcpp::wrap(interp_xyzc(inp, ix, iy, iz, ic, cubic));
    return rcpp_result_gen;
END_RCPP
}
// interp_xyc
NumericVector interp_xyc(NumericVector inp, NumericVector ix, NumericVector iy, int z, IntegerVector ic, bool cubic);
RcppExport SEXP imager_interp_xyc(SEXP inpSEXP, SEXP ixSEXP, SEXP iySEXP, SEXP zSEXP, SEXP icSEXP, SEXP cubicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inp(inpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iy(iySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ic(icSEXP);
    Rcpp::traits::input_parameter< bool >::type cubic(cubicSEXP);
    rcpp_result_gen = Rcpp::wrap(interp_xyc(inp, ix, iy, z, ic, cubic));
    return rcpp_result_gen;
END_RCPP
}
// label
NumericVector label(NumericVector im, bool high_connectivity, double tolerance);
RcppExport SEXP imager_label(SEXP imSEXP, SEXP high_connectivitySEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< bool >::type high_connectivity(high_connectivitySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(label(im, high_connectivity, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// blabel
NumericVector blabel(LogicalVector im, bool high_connectivity);
RcppExport SEXP imager_blabel(SEXP imSEXP, SEXP high_connectivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< bool >::type high_connectivity(high_connectivitySEXP);
    rcpp_result_gen = Rcpp::wrap(blabel(im, high_connectivity));
    return rcpp_result_gen;
END_RCPP
}
// erode
NumericVector erode(NumericVector im, NumericVector mask, bool boundary_conditions, bool real_mode);
RcppExport SEXP imager_erode(SEXP imSEXP, SEXP maskSEXP, SEXP boundary_conditionsSEXP, SEXP real_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< bool >::type boundary_conditions(boundary_conditionsSEXP);
    Rcpp::traits::input_parameter< bool >::type real_mode(real_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(erode(im, mask, boundary_conditions, real_mode));
    return rcpp_result_gen;
END_RCPP
}
// berode
LogicalVector berode(LogicalVector im, LogicalVector mask, bool boundary_conditions);
RcppExport SEXP imager_berode(SEXP imSEXP, SEXP maskSEXP, SEXP boundary_conditionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< bool >::type boundary_conditions(boundary_conditionsSEXP);
    rcpp_result_gen = Rcpp::wrap(berode(im, mask, boundary_conditions));
    return rcpp_result_gen;
END_RCPP
}
// erode_rect
NumericVector erode_rect(NumericVector im, int sx, int sy, int sz);
RcppExport SEXP imager_erode_rect(SEXP imSEXP, SEXP sxSEXP, SEXP sySEXP, SEXP szSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< int >::type sy(sySEXP);
    Rcpp::traits::input_parameter< int >::type sz(szSEXP);
    rcpp_result_gen = Rcpp::wrap(erode_rect(im, sx, sy, sz));
    return rcpp_result_gen;
END_RCPP
}
// berode_rect
LogicalVector berode_rect(LogicalVector im, int sx, int sy, int sz);
RcppExport SEXP imager_berode_rect(SEXP imSEXP, SEXP sxSEXP, SEXP sySEXP, SEXP szSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< int >::type sy(sySEXP);
    Rcpp::traits::input_parameter< int >::type sz(szSEXP);
    rcpp_result_gen = Rcpp::wrap(berode_rect(im, sx, sy, sz));
    return rcpp_result_gen;
END_RCPP
}
// erode_square
NumericVector erode_square(NumericVector im, int size);
RcppExport SEXP imager_erode_square(SEXP imSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(erode_square(im, size));
    return rcpp_result_gen;
END_RCPP
}
// berode_square
LogicalVector berode_square(LogicalVector im, int size);
RcppExport SEXP imager_berode_square(SEXP imSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(berode_square(im, size));
    return rcpp_result_gen;
END_RCPP
}
// dilate
NumericVector dilate(NumericVector im, NumericVector mask, bool boundary_conditions, bool real_mode);
RcppExport SEXP imager_dilate(SEXP imSEXP, SEXP maskSEXP, SEXP boundary_conditionsSEXP, SEXP real_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< bool >::type boundary_conditions(boundary_conditionsSEXP);
    Rcpp::traits::input_parameter< bool >::type real_mode(real_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(dilate(im, mask, boundary_conditions, real_mode));
    return rcpp_result_gen;
END_RCPP
}
// bdilate
LogicalVector bdilate(LogicalVector im, LogicalVector mask, bool boundary_conditions);
RcppExport SEXP imager_bdilate(SEXP imSEXP, SEXP maskSEXP, SEXP boundary_conditionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< bool >::type boundary_conditions(boundary_conditionsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdilate(im, mask, boundary_conditions));
    return rcpp_result_gen;
END_RCPP
}
// dilate_rect
NumericVector dilate_rect(NumericVector im, int sx, int sy, int sz);
RcppExport SEXP imager_dilate_rect(SEXP imSEXP, SEXP sxSEXP, SEXP sySEXP, SEXP szSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< int >::type sy(sySEXP);
    Rcpp::traits::input_parameter< int >::type sz(szSEXP);
    rcpp_result_gen = Rcpp::wrap(dilate_rect(im, sx, sy, sz));
    return rcpp_result_gen;
END_RCPP
}
// bdilate_rect
LogicalVector bdilate_rect(LogicalVector im, int sx, int sy, int sz);
RcppExport SEXP imager_bdilate_rect(SEXP imSEXP, SEXP sxSEXP, SEXP sySEXP, SEXP szSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< int >::type sy(sySEXP);
    Rcpp::traits::input_parameter< int >::type sz(szSEXP);
    rcpp_result_gen = Rcpp::wrap(bdilate_rect(im, sx, sy, sz));
    return rcpp_result_gen;
END_RCPP
}
// dilate_square
NumericVector dilate_square(NumericVector im, int size);
RcppExport SEXP imager_dilate_square(SEXP imSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(dilate_square(im, size));
    return rcpp_result_gen;
END_RCPP
}
// bdilate_square
LogicalVector bdilate_square(LogicalVector im, int size);
RcppExport SEXP imager_bdilate_square(SEXP imSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(bdilate_square(im, size));
    return rcpp_result_gen;
END_RCPP
}
// watershed
NumericVector watershed(NumericVector im, NumericVector priority, bool fill_lines);
RcppExport SEXP imager_watershed(SEXP imSEXP, SEXP prioritySEXP, SEXP fill_linesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type priority(prioritySEXP);
    Rcpp::traits::input_parameter< bool >::type fill_lines(fill_linesSEXP);
    rcpp_result_gen = Rcpp::wrap(watershed(im, priority, fill_lines));
    return rcpp_result_gen;
END_RCPP
}
// distance_transform
NumericVector distance_transform(NumericVector im, double value, unsigned int metric);
RcppExport SEXP imager_distance_transform(SEXP imSEXP, SEXP valueSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_transform(im, value, metric));
    return rcpp_result_gen;
END_RCPP
}
// bdistance_transform
NumericVector bdistance_transform(LogicalVector im, bool value, unsigned int metric);
RcppExport SEXP imager_bdistance_transform(SEXP imSEXP, SEXP valueSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< bool >::type value(valueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(bdistance_transform(im, value, metric));
    return rcpp_result_gen;
END_RCPP
}
// mopening
NumericVector mopening(NumericVector im, NumericVector mask, bool boundary_conditions, bool real_mode);
RcppExport SEXP imager_mopening(SEXP imSEXP, SEXP maskSEXP, SEXP boundary_conditionsSEXP, SEXP real_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< bool >::type boundary_conditions(boundary_conditionsSEXP);
    Rcpp::traits::input_parameter< bool >::type real_mode(real_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(mopening(im, mask, boundary_conditions, real_mode));
    return rcpp_result_gen;
END_RCPP
}
// mopening_square
NumericVector mopening_square(NumericVector im, int size);
RcppExport SEXP imager_mopening_square(SEXP imSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(mopening_square(im, size));
    return rcpp_result_gen;
END_RCPP
}
// mclosing_square
NumericVector mclosing_square(NumericVector im, int size);
RcppExport SEXP imager_mclosing_square(SEXP imSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(mclosing_square(im, size));
    return rcpp_result_gen;
END_RCPP
}
// mclosing
NumericVector mclosing(NumericVector im, NumericVector mask, bool boundary_conditions, bool real_mode);
RcppExport SEXP imager_mclosing(SEXP imSEXP, SEXP maskSEXP, SEXP boundary_conditionsSEXP, SEXP real_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< bool >::type boundary_conditions(boundary_conditionsSEXP);
    Rcpp::traits::input_parameter< bool >::type real_mode(real_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(mclosing(im, mask, boundary_conditions, real_mode));
    return rcpp_result_gen;
END_RCPP
}
// reduce_wsum
NumericVector reduce_wsum(List x, NumericVector w, bool na_rm);
RcppExport SEXP imager_reduce_wsum(SEXP xSEXP, SEXP wSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_wsum(x, w, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// reduce_average
NumericVector reduce_average(List x, bool na_rm);
RcppExport SEXP imager_reduce_average(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_average(x, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// reduce_prod
NumericVector reduce_prod(List x, bool na_rm);
RcppExport SEXP imager_reduce_prod(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_prod(x, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// reduce_minmax
NumericVector reduce_minmax(List x, bool na_rm, bool max);
RcppExport SEXP imager_reduce_minmax(SEXP xSEXP, SEXP na_rmSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_minmax(x, na_rm, max));
    return rcpp_result_gen;
END_RCPP
}
// reduce_list
NumericVector reduce_list(List x, int summary);
RcppExport SEXP imager_reduce_list(SEXP xSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_list(x, summary));
    return rcpp_result_gen;
END_RCPP
}
// reduce_list2
NumericVector reduce_list2(List x, int summary);
RcppExport SEXP imager_reduce_list2(SEXP xSEXP, SEXP summarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type summary(summarySEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_list2(x, summary));
    return rcpp_result_gen;
END_RCPP
}
// reduce_med
NumericVector reduce_med(List x, bool na_rm);
RcppExport SEXP imager_reduce_med(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_med(x, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// psort
List psort(List x, bool increasing);
RcppExport SEXP imager_psort(SEXP xSEXP, SEXP increasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type increasing(increasingSEXP);
    rcpp_result_gen = Rcpp::wrap(psort(x, increasing));
    return rcpp_result_gen;
END_RCPP
}
// porder
List porder(List x, bool increasing);
RcppExport SEXP imager_porder(SEXP xSEXP, SEXP increasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type increasing(increasingSEXP);
    rcpp_result_gen = Rcpp::wrap(porder(x, increasing));
    return rcpp_result_gen;
END_RCPP
}
// prank
List prank(List x, bool increasing);
RcppExport SEXP imager_prank(SEXP xSEXP, SEXP increasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type increasing(increasingSEXP);
    rcpp_result_gen = Rcpp::wrap(prank(x, increasing));
    return rcpp_result_gen;
END_RCPP
}
// autocrop_
NumericVector autocrop_(NumericVector im, NumericVector color, std::string axes);
RcppExport SEXP imager_autocrop_(SEXP imSEXP, SEXP colorSEXP, SEXP axesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    Rcpp::traits::input_parameter< std::string >::type axes(axesSEXP);
    rcpp_result_gen = Rcpp::wrap(autocrop_(im, color, axes));
    return rcpp_result_gen;
END_RCPP
}
// rotate
NumericVector rotate(NumericVector im, float angle, unsigned int interpolation, unsigned int boundary);
RcppExport SEXP imager_rotate(SEXP imSEXP, SEXP angleSEXP, SEXP interpolationSEXP, SEXP boundarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type angle(angleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type interpolation(interpolationSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type boundary(boundarySEXP);
    rcpp_result_gen = Rcpp::wrap(rotate(im, angle, interpolation, boundary));
    return rcpp_result_gen;
END_RCPP
}
// rotate_xy
NumericVector rotate_xy(NumericVector im, float angle, float cx, float cy, unsigned int interpolation, unsigned int boundary_conditions);
RcppExport SEXP imager_rotate_xy(SEXP imSEXP, SEXP angleSEXP, SEXP cxSEXP, SEXP cySEXP, SEXP interpolationSEXP, SEXP boundary_conditionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< float >::type angle(angleSEXP);
    Rcpp::traits::input_parameter< float >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< float >::type cy(cySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type interpolation(interpolationSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type boundary_conditions(boundary_conditionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rotate_xy(im, angle, cx, cy, interpolation, boundary_conditions));
    return rcpp_result_gen;
END_RCPP
}
// mirror
NumericVector mirror(NumericVector im, char axis);
RcppExport SEXP imager_mirror(SEXP imSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(mirror(im, axis));
    return rcpp_result_gen;
END_RCPP
}
// permute_axes
NumericVector permute_axes(NumericVector im, std::string perm);
RcppExport SEXP imager_permute_axes(SEXP imSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< std::string >::type perm(permSEXP);
    rcpp_result_gen = Rcpp::wrap(permute_axes(im, perm));
    return rcpp_result_gen;
END_RCPP
}
// resize_doubleXY
NumericVector resize_doubleXY(NumericVector im);
RcppExport SEXP imager_resize_doubleXY(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(resize_doubleXY(im));
    return rcpp_result_gen;
END_RCPP
}
// resize_halfXY
NumericVector resize_halfXY(NumericVector im);
RcppExport SEXP imager_resize_halfXY(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(resize_halfXY(im));
    return rcpp_result_gen;
END_RCPP
}
// resize_tripleXY
NumericVector resize_tripleXY(NumericVector im);
RcppExport SEXP imager_resize_tripleXY(SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(resize_tripleXY(im));
    return rcpp_result_gen;
END_RCPP
}
// imshift
NumericVector imshift(NumericVector im, int delta_x, int delta_y, int delta_z, int delta_c, int boundary_conditions);
RcppExport SEXP imager_imshift(SEXP imSEXP, SEXP delta_xSEXP, SEXP delta_ySEXP, SEXP delta_zSEXP, SEXP delta_cSEXP, SEXP boundary_conditionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type delta_x(delta_xSEXP);
    Rcpp::traits::input_parameter< int >::type delta_y(delta_ySEXP);
    Rcpp::traits::input_parameter< int >::type delta_z(delta_zSEXP);
    Rcpp::traits::input_parameter< int >::type delta_c(delta_cSEXP);
    Rcpp::traits::input_parameter< int >::type boundary_conditions(boundary_conditionsSEXP);
    rcpp_result_gen = Rcpp::wrap(imshift(im, delta_x, delta_y, delta_z, delta_c, boundary_conditions));
    return rcpp_result_gen;
END_RCPP
}
// resize
NumericVector resize(NumericVector im, int size_x, int size_y, int size_z, int size_c, int interpolation_type, unsigned int boundary_conditions, float centering_x, float centering_y, float centering_z, float centering_c);
RcppExport SEXP imager_resize(SEXP imSEXP, SEXP size_xSEXP, SEXP size_ySEXP, SEXP size_zSEXP, SEXP size_cSEXP, SEXP interpolation_typeSEXP, SEXP boundary_conditionsSEXP, SEXP centering_xSEXP, SEXP centering_ySEXP, SEXP centering_zSEXP, SEXP centering_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type size_x(size_xSEXP);
    Rcpp::traits::input_parameter< int >::type size_y(size_ySEXP);
    Rcpp::traits::input_parameter< int >::type size_z(size_zSEXP);
    Rcpp::traits::input_parameter< int >::type size_c(size_cSEXP);
    Rcpp::traits::input_parameter< int >::type interpolation_type(interpolation_typeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type boundary_conditions(boundary_conditionsSEXP);
    Rcpp::traits::input_parameter< float >::type centering_x(centering_xSEXP);
    Rcpp::traits::input_parameter< float >::type centering_y(centering_ySEXP);
    Rcpp::traits::input_parameter< float >::type centering_z(centering_zSEXP);
    Rcpp::traits::input_parameter< float >::type centering_c(centering_cSEXP);
    rcpp_result_gen = Rcpp::wrap(resize(im, size_x, size_y, size_z, size_c, interpolation_type, boundary_conditions, centering_x, centering_y, centering_z, centering_c));
    return rcpp_result_gen;
END_RCPP
}
// warp
NumericVector warp(NumericVector im, NumericVector warpfield, unsigned int mode, unsigned int interpolation, unsigned int boundary_conditions);
RcppExport SEXP imager_warp(SEXP imSEXP, SEXP warpfieldSEXP, SEXP modeSEXP, SEXP interpolationSEXP, SEXP boundary_conditionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type warpfield(warpfieldSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type interpolation(interpolationSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type boundary_conditions(boundary_conditionsSEXP);
    rcpp_result_gen = Rcpp::wrap(warp(im, warpfield, mode, interpolation, boundary_conditions));
    return rcpp_result_gen;
END_RCPP
}
// load_image
NumericVector load_image(std::string fname);
RcppExport SEXP imager_load_image(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    rcpp_result_gen = Rcpp::wrap(load_image(fname));
    return rcpp_result_gen;
END_RCPP
}
// save_image
void save_image(NumericVector im, std::string fname);
RcppExport SEXP imager_save_image(SEXP imSEXP, SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    save_image(im, fname);
    return R_NilValue;
END_RCPP
}
// im_split
List im_split(NumericVector im, char axis, int nb);
RcppExport SEXP imager_im_split(SEXP imSEXP, SEXP axisSEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    rcpp_result_gen = Rcpp::wrap(im_split(im, axis, nb));
    return rcpp_result_gen;
END_RCPP
}
// im_append
NumericVector im_append(List imlist, char axis);
RcppExport SEXP imager_im_append(SEXP imlistSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type imlist(imlistSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(im_append(imlist, axis));
    return rcpp_result_gen;
END_RCPP
}
// px_append
LogicalVector px_append(List imlist, char axis);
RcppExport SEXP imager_px_append(SEXP imlistSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type imlist(imlistSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(px_append(imlist, axis));
    return rcpp_result_gen;
END_RCPP
}
// imeval
NumericVector imeval(NumericVector im, std::string expr);
RcppExport SEXP imager_imeval(SEXP imSEXP, SEXP exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< std::string >::type expr(exprSEXP);
    rcpp_result_gen = Rcpp::wrap(imeval(im, expr));
    return rcpp_result_gen;
END_RCPP
}
// patch_summary_cimg
NumericVector patch_summary_cimg(NumericVector im, std::string expr, IntegerVector cx, IntegerVector cy, IntegerVector wx, IntegerVector wy);
RcppExport SEXP imager_patch_summary_cimg(SEXP imSEXP, SEXP exprSEXP, SEXP cxSEXP, SEXP cySEXP, SEXP wxSEXP, SEXP wySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< std::string >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cy(cySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wx(wxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wy(wySEXP);
    rcpp_result_gen = Rcpp::wrap(patch_summary_cimg(im, expr, cx, cy, wx, wy));
    return rcpp_result_gen;
END_RCPP
}
// extract_fast
NumericVector extract_fast(NumericVector im, int fun, IntegerVector cx, IntegerVector cy, IntegerVector wx, IntegerVector wy);
RcppExport SEXP imager_extract_fast(SEXP imSEXP, SEXP funSEXP, SEXP cxSEXP, SEXP cySEXP, SEXP wxSEXP, SEXP wySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type fun(funSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cy(cySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wx(wxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wy(wySEXP);
    rcpp_result_gen = Rcpp::wrap(extract_fast(im, fun, cx, cy, wx, wy));
    return rcpp_result_gen;
END_RCPP
}
// extract_patches
List extract_patches(NumericVector im, IntegerVector cx, IntegerVector cy, IntegerVector wx, IntegerVector wy);
RcppExport SEXP imager_extract_patches(SEXP imSEXP, SEXP cxSEXP, SEXP cySEXP, SEXP wxSEXP, SEXP wySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cy(cySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wx(wxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wy(wySEXP);
    rcpp_result_gen = Rcpp::wrap(extract_patches(im, cx, cy, wx, wy));
    return rcpp_result_gen;
END_RCPP
}
// extract_patches3D
List extract_patches3D(NumericVector im, IntegerVector cx, IntegerVector cy, IntegerVector cz, IntegerVector wx, IntegerVector wy, IntegerVector wz);
RcppExport SEXP imager_extract_patches3D(SEXP imSEXP, SEXP cxSEXP, SEXP cySEXP, SEXP czSEXP, SEXP wxSEXP, SEXP wySEXP, SEXP wzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cy(cySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cz(czSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wx(wxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wy(wySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wz(wzSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_patches3D(im, cx, cy, cz, wx, wy, wz));
    return rcpp_result_gen;
END_RCPP
}
// draw_image
NumericVector draw_image(NumericVector im, NumericVector sprite, int x, int y, int z, float opacity);
RcppExport SEXP imager_draw_image(SEXP imSEXP, SEXP spriteSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP opacitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sprite(spriteSEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< float >::type opacity(opacitySEXP);
    rcpp_result_gen = Rcpp::wrap(draw_image(im, sprite, x, y, z, opacity));
    return rcpp_result_gen;
END_RCPP
}
// do_patchmatch
List do_patchmatch(NumericVector im1, NumericVector im2, unsigned int patch_width, unsigned int patch_height, unsigned int patch_depth, unsigned int nb_iterations, unsigned int nb_randoms, NumericVector guide);
RcppExport SEXP imager_do_patchmatch(SEXP im1SEXP, SEXP im2SEXP, SEXP patch_widthSEXP, SEXP patch_heightSEXP, SEXP patch_depthSEXP, SEXP nb_iterationsSEXP, SEXP nb_randomsSEXP, SEXP guideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im1(im1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type im2(im2SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type patch_width(patch_widthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type patch_height(patch_heightSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type patch_depth(patch_depthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nb_iterations(nb_iterationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nb_randoms(nb_randomsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type guide(guideSEXP);
    rcpp_result_gen = Rcpp::wrap(do_patchmatch(im1, im2, patch_width, patch_height, patch_depth, nb_iterations, nb_randoms, guide));
    return rcpp_result_gen;
END_RCPP
}
// checkcoords
LogicalVector checkcoords(IntegerVector x, IntegerVector y, IntegerVector z, IntegerVector c, IntegerVector d);
RcppExport SEXP imager_checkcoords(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP cSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(checkcoords(x, y, z, c, d));
    return rcpp_result_gen;
END_RCPP
}
// cimg_omp
int cimg_omp();
RcppExport SEXP imager_cimg_omp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cimg_omp());
    return rcpp_result_gen;
END_RCPP
}
// set_cimg_omp
int set_cimg_omp(int mode);
RcppExport SEXP imager_set_cimg_omp(SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(set_cimg_omp(mode));
    return rcpp_result_gen;
END_RCPP
}
// has_omp
bool has_omp();
RcppExport SEXP imager_has_omp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_omp());
    return rcpp_result_gen;
END_RCPP
}
// px_split
List px_split(LogicalVector im, char axis, int nb);
RcppExport SEXP imager_px_split(SEXP imSEXP, SEXP axisSEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< char >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    rcpp_result_gen = Rcpp::wrap(px_split(im, axis, nb));
    return rcpp_result_gen;
END_RCPP
}
